[ req ]
default_bits        = 2048
default_md          = sha256
default_keyfile     = server.key    # Default private key file
distinguished_name  = req_distinguished_name
req_extensions      = req_ext       # Extensions for certificate request
x509_extensions     = v3_ca         # Extensions for self-signed certificate
prompt              = no            # Don't prompt for DN info

[ req_distinguished_name ]
C  = GB                       # Country (2 letter code)
ST = Cambridgeshire                 # State or Province
L  = Cambridge            # Locality
O  = GRNO               # Organization Name
OU = Bredlab            # Organizational Unit
CN = CC2                # Common Name (domain)

[ req_ext ]
subjectAltName = @alt_names

[ v3_ca ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = localhost